# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Humanes
email: ideler.dennis+humanes@gmail.com
description: > # description appears in head meta (for pagerank) and feed.xml
  Software consulting and bespoke application development
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://humanes.github.io"
github_username: humanes
twitter_username: dideler
google_analytics: UA-104914585-1

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
